### ISSUE TITLE
How to survive with dynamic graphics

### ISSUE THREAD

**Issue by nss6planner** [taewankim1/robust_mpc_obstacle_avoidance#1]
Hello, may I ask which python script this gif image is generated by running? I see that all script codes do not reference utils to generate images.

**Comment by taewankim1** [comment]
Hi,

See each 01-06 notebook file in the "notebooks" folder.

**Comment by nss6planner** [comment]
Hello, I am very happy to receive your recovery. I couldn't wait to run the code, but the following error occurred when running. How should I solve it? I have been trying for a long time.

None FAIL: ValueError
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-7-d498d1391773> in <module>
----> 1 xfwd,ufwd,xnom,unom,tfnom,total_num_iter,l_all,l_tf,l_vc,l_tr,history_nom  = TrajOpt.run(x0,u0,xi,xf)
      2 print("final time {:}".format(tfnom))

~/robust_mpc_obstacle_avoidance/PTR_tf_free.py in run(self, x0, u0, xi, xf)
    302             # step2. cvxopt
    303             tic = time.time()
--> 304             l_all,l_tf,l_vc,l_tr,self.xnew,self.unew,self.tfnew,self.vcnew,error = self.cvxopt()
    305             history_iter['cvxopt'] = time.time() - tic
    306             history_iter['flag_cvxopt_error'] = error

~/robust_mpc_obstacle_avoidance/PTR_tf_free.py in cvxopt(self)
    264         return self.cvx_cost['l_all'].value,self.cvx_cost['l_tf'].value, \
    265                 self.cvx_cost['l_vc'].value,self.cvx_cost['l_tr'].value, \
--> 266                 xnew,unew,sigmanew,vc,error
    267 
    268     def run(self,x0,u0,xi,xf=None):

UnboundLocalError: local variable 'sigmanew' referenced before assignment

**Comment by nss6planner** [comment]
> 你好，
> 
> 请参阅“笔记本”文件夹中的每个 01-06 笔记本文件。

Hello, I am very happy to receive your recovery. I couldn't wait to run the code, but the following error occurred when running. How should I solve it? I have been trying for a long time.

None FAIL: ValueError
UnboundLocalError Traceback (most recent call last)
in
----> 1 xfwd,ufwd,xnom,unom,tfnom,total_num_iter,l_all,l_tf,l_vc,l_tr,history_nom = TrajOpt.run(x0,u0,xi,xf)
2 print("final time {:}".format(tfnom))

~/robust_mpc_obstacle_avoidance/PTR_tf_free.py in run(self, x0, u0, xi, xf)
302 # step2. cvxopt
303 tic = time.time()
--> 304 l_all,l_tf,l_vc,l_tr,self.xnew,self.unew,self.tfnew,self.vcnew,error = self.cvxopt()
305 history_iter['cvxopt'] = time.time() - tic
306 history_iter['flag_cvxopt_error'] = error

~/robust_mpc_obstacle_avoidance/PTR_tf_free.py in cvxopt(self)
264 return self.cvx_cost['l_all'].value,self.cvx_cost['l_tf'].value,
265 self.cvx_cost['l_vc'].value,self.cvx_cost['l_tr'].value,
--> 266 xnew,unew,sigmanew,vc,error
267
268 def run(self,x0,u0,xi,xf=None):

UnboundLocalError: local variable 'sigmanew' referenced before assignment

**Comment by nss6planner** [comment]
> 你好，
> 
> 请参阅“笔记本”文件夹中的每个 01-06 笔记本文件。

Hello, I'm glad to receive your answer. I couldn't wait to run the code, but the following error occurred when running. How should I solve it? I have been trying for a long time.
None FAIL: ValueError
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-7-d498d1391773> in <module>
----> 1 xfwd,ufwd,xnom,unom,tfnom,total_num_iter,l_all,l_tf,l_vc,l_tr,history_nom  = TrajOpt.run(x0,u0,xi,xf)
      2 print("final time {:}".format(tfnom))

~/robust_mpc_obstacle_avoidance/PTR_tf_free.py in run(self, x0, u0, xi, xf)
    302             # step2. cvxopt
    303             tic = time.time()
--> 304             l_all,l_tf,l_vc,l_tr,self.xnew,self.unew,self.tfnew,self.vcnew,error = self.cvxopt()
    305             history_iter['cvxopt'] = time.time() - tic
    306             history_iter['flag_cvxopt_error'] = error

~/robust_mpc_obstacle_avoidance/PTR_tf_free.py in cvxopt(self)
    264         return self.cvx_cost['l_all'].value,self.cvx_cost['l_tf'].value, \
    265                 self.cvx_cost['l_vc'].value,self.cvx_cost['l_tr'].value, \
--> 266                 xnew,unew,sigmanew,vc,error
    267 
    268     def run(self,x0,u0,xi,xf=None):

UnboundLocalError: local variable 'sigmanew' referenced before assignment

**Comment by nss6planner** [comment]
> 你好，
> 
> 请参阅“笔记本”文件夹中的每个 01-06 笔记本文件。

Hello, I'm glad to receive your answer. I can't wait to run the code.

**Comment by nss6planner** [comment]
> 你好，
> 
> 请参阅“笔记本”文件夹中的每个 01-06 笔记本文件。

Hello, I got an error when I called the PTR_tf_free.py file at runtime and was unable to find the optimal solution. According to your requirements, I tried both the Gurobi solver and the ECOS solver and still got an error. The error message is as follows:
AssertionError                            Traceback (most recent call last)
<ipython-input-34-d498d1391773> in <module>
----> 1 xfwd,ufwd,xnom,unom,tfnom,total_num_iter,l_all,l_tf,l_vc,l_tr,history_nom  = TrajOpt.run(x0,u0,xi,xf)
      2 print("final time {:}".format(tfnom))

~/robust_mpc_obstacle_avoidance/PTR_tf_free.py in run(self, x0, u0, xi, xf)
    304             # differentiate dynamics and cost
    305             tic = time.time()
--> 306             self.A,self.B,self.Bm,self.Bp,self.s,self.z,self.x_prop,self.x_prop_n = self.get_linearized_matrices(self.x,self.u,self.delT,self.tf)
    307             history_iter['derivs'] = time.time() - tic
    308 

~/robust_mpc_obstacle_avoidance/PTR.py in get_linearized_matrices(self, x, u, delT, tf)
     98             # A,Bm,Bp,s,z,x_prop_n = self.model.diff_discrete_foh(x[0:self.N,:],u,delT,tf)
     99             # A,Bm,Bp,s,z,x_prop_n = self.model.diff_discrete_foh_tau(x[0:self.N,:],u,1/self.N,tf)
--> 100             A,Bm,Bp,s,z,x_prop_n = self.model.diff_discrete_foh_variational(x[0:self.N,:],u,1/self.N,tf)
    101             x_prop = np.squeeze(A@np.expand_dims(x[0:self.N,:],2) +
    102                             Bm@np.expand_dims(u[0:self.N,:],2) +

~/robust_mpc_obstacle_avoidance/model/model.py in diff_discrete_foh_variational(self, x, u, dtau, tf)
    647         # sol = solve_ivp(dvdt,(0,dtau),V0_repeat,args=(u[0:N],u[1:],N),rtol=1e-6,atol=1e-10)
    648         # sol = solve_ivp(dvdt,(0,dtau),V0_repeat,args=(u[0:N],u[1:],N))
--> 649         sol = RK4(dvdt,(0,dtau),V0_repeat,args=(u[0:N],u[1:],N),N_RK=50)
    650 
    651         sol = sol.y[:,-1].reshape((N,-1))

~/robust_mpc_obstacle_avoidance/model/model.py in RK4(odefun, tspan, y0, args, N_RK)
     26         tk = t[idx]
     27         yk = y_sol[idx]
---> 28         k1 = odefun(tk,yk,*args)
     29         k2 = odefun(tk + h/2,yk + h/2*k1,*args)
     30         k3 = odefun(tk + h/2,yk + h/2*k2,*args)

~/robust_mpc_obstacle_avoidance/model/model.py in dvdt(t, V, um, up, length)
    605         # idx_z = slice(ix+ix*ix+2*ix*iu+ix,ix+ix*ix+2*ix*iu+ix+ix)
    606         def dvdt(t,V,um,up,length) :
--> 607             assert len(um) == len(up)
    608             assert len(um) == length
    609             alpha = (dtau - t) / dtau

AssertionError:

**Comment by taewankim1** [comment]
Which notebook file did you run?

**Comment by nss6planner** [comment]
> 您运行了哪个笔记本文件？


Thank you very much, I have successfully run

**Comment by nss6planner** [comment]
Hello, I would like to ask if you replace the unicycle model with a quadcopter drone model, which files need to be modified, and can the whole set of system files support the drone model to achieve obstacle avoidance?

**Comment by taewankim1** [comment]
Hi, actually there are a plenty of things you need to change to implement the quadrotor model, including "model" and "constraint".  The code for solver of optimal control is "PTR" and "PTR_tf_free", and these codes are converted into "PTR_in_MPC" for receding horizon scheme. You may not need to change these "PTR" codes, but not sure.

**Comment by nss6planner** [comment]
> 嗨，实际上，要实现四旋翼模型，您需要更改很多东西，包括“模型”和“约束”。最优控制求解器的代码为“PTR”和“PTR_tf_free”，这些代码转换为“PTR_in_MPC”表示后退地平线方案。您可能不需要更改这些“PTR”代码，但不确定。

Hello, I found the quadrotor model in your sequential_convex_programming
I found quadrotor model in your repository, and I have more problems when combining them, the most problem is that the function accepts inconsistent parameters, the original cart only needs four parameters, while quadrotor needs six parameters, I would like to consult you if there is any literature related to dynamic obstacle avoidance of UAVs through forward stochastic reachable and combining with MPC controllers that can be referred to, help! Modify the code of PTR_in_MPC. The main error reporting that occurs is as follows:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_17960\1662349477.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/%E6%9C%89%E5%85%B3mpc%E4%BB%A3%E7%A0%81%E5%8C%85/robust_mpc_obstacle_avoidance-main/notebooks/~/AppData/Local/Temp/ipykernel_17960/1662349477.py) in <module>
      6 MPC_controller = PTR_in_MPC('quadrotors',Nmpc,horizon,max_iter,myModel,MPC_Cost,MPC_Const,myScaling,
      7           type_discretization="zoh",w_c=1,w_vc=1e3,w_tr=1e-1,
----> 8                             tol_vc=1e-6,tol_tr=1e-3,verbosity=False)

\robust_mpc_obstacle_avoidance-main\PTR_in_MPC.py in __init__(self, name, horizon, tf, maxIter, Model, Cost, Const, Scaling, type_discretization, w_c, w_vc, w_tr, tol_vc, tol_tr, tol_dyn, verbosity)
     46         self.type_discretization = type_discretization    
     47         self.initialize()
---> 48         self.cvx_initialize()
     49 
     50     def initialize(self) : 



    161         for i in range(0,N+1) :
--> 162             cost_c.append(self.w_c * self.cost.estimate_cost_cvx(Sx@xcvx[i]+sx,Su@ucvx[i]+su,xtrj[i],utrj[i],i)) #
    163             if i < N : #if i < N: 
    164                 cost_vc.append(cvx.norm(vc[i],1)) 

TypeError: estimate_cost_cvx() takes 4 positional arguments but 6 were given

Also, I'd like to ask you where do you download the Scvx repository? I get an error running it:
ModuleNotFoundError: No module named 'Scvx'

**Comment by taewankim1** [comment]
Hi, Yes. It would not be straightforward to implement the quadrotor model given in that repository. Most of code in this reposit are fitted specifically to the unicycle model. I believe, currently, the quadrotor model is not applicable even in the repository you mentioned.
